# Generated by Django 5.2.4 on 2025-07-22 16:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock disponible')),
                ('categoria', models.CharField(choices=[('electronica', 'Electrónica'), ('ropa', 'Ropa'), ('hogar', 'Hogar'), ('deportes', 'Deportes'), ('libros', 'Libros'), ('otros', 'Otros')], default='otros', max_length=20, verbose_name='Categoría')),
                ('activo', models.BooleanField(default=True, verbose_name='Producto activo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-creado'],
            },
        ),
    ]
